### ISSUE TITLE
Split default-font var into default-sans-font and default-serif-font?

### ISSUE THREAD

**Issue by seanwash** [octopuscreative/decent-scss#7]

**Comment by chrsgrffth** [comment]
Maybe something less specific (primary/secondary, main/secondary, body/display)? For cases where a slab-serif or monospaced font may be used.

**Comment by chrsgrffth** [comment]
There are now 2 variables for type families:

`$default-type-family` should be associated with body copy (because the rem base is derived from this as well). `$display-type-family` should be associated with a secondary font that is used for headings, links, quotes, etc.

This way we don't have to change the actual declarations in `type.scss` if the body copy switches from a sans to a serif font.
